"""Auto-generated AutoLSTM Optuna configuration.

Generated by config_agent.py.
Do not edit manually unless you intentionally want to override
the agent-generated search space.
"""


def autolstm_config(trial):
    return {
        "input_size": trial.suggest_categorical("input_size", [8, 16, 32, 64, 128]),
        "inference_input_size": -1,
        "encoder_hidden_size": trial.suggest_categorical("encoder_hidden_size", [16, 32, 64]),
        "encoder_n_layers": trial.suggest_int("encoder_n_layers", 1, 3),
        "context_size": trial.suggest_categorical("context_size", [5, 10]),
        "decoder_hidden_size": trial.suggest_categorical("decoder_hidden_size", [16, 32, 64]),
        "learning_rate": trial.suggest_float("learning_rate", 0.0001, 0.01, log=True),
        "max_steps": trial.suggest_categorical("max_steps", [300, 500, 1000]),
        "batch_size": trial.suggest_categorical("batch_size", [16, 32]),
        "random_seed": trial.suggest_int("random_seed", 1, 20),
        "scaler_type": 'standard',
    }
